spring.application.name=portafolio-api
# Configuración del puerto del servidor
server.port=8080

spring.mongodb.uri=mongodb+srv://superadmin:Lopera2026.@david-lopera.fwegtcn.mongodb.net/portafolio_db?appName=David-Lopera